openapi: 3.0.1
info:
  title: API de Carrito
  description: Documentación de las rutas relacionadas con el carrito de compras.
  version: 1.0.0
tags:
- name: Carrito
  description: Endpoints para agregar, eliminar, y ver productos en el carrito.
paths:
  /api/cart/{cid}:
    get:
      tags: 
      - Carrito
      summary: Obtener un carrito por su ID
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
          description: ID del carrito
      responses:
        '200':
          description: OK. Devuelve el carrito solicitado.
        '404':
          description: The cart you trying to add a product doesn't exists.

  /api/cart:
    post:
      tags: 
      - Carrito
      summary: Crear un nuevo carrito
      responses:
        '201':
          description: Cart created successfully.
        '400':
          description: The cart creation encountered an error.

  /api/cart/product:
    post:
      tags: 
      - Carrito
      summary: Agregar un producto al carrito
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cid:
                  type: string
                pid:
                  type: string
      responses:
        '200':
          description: Product has added to cart {cid}.
        '404':
          description: The product you are trying to add does not exist in the database.

  /api/cart/products:
    put:
      tags: 
      - Carrito
      summary: Actualizar la cantidad de un producto en el carrito
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cid:
                  type: string
                pid:
                  type: string
                quantity:
                  type: integer
      responses:
        '200':
          description: Quantity updated successfully.
        '404':
          description: There is no product or cart to update the quantity for.
          
    delete:
      tags: 
      - Carrito
      summary: Eliminar un producto del carrito
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cid:
                  type: string
                pid:
                  type: string
      responses:
        '200':
          description: The product has been deleted from cart.
        '404':
          description: The product you want to delete either does not exist or has already been deleted.
